// Generated by CoffeeScript 1.6.3
(function() {
  var VoilaPlugin;

  module.exports = function(game, opts) {
    return new VoilaPlugin(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['voxel-highlight', 'voxel-registry']
  };

  VoilaPlugin = (function() {
    function VoilaPlugin(game, opts) {
      var _ref, _ref1;
      this.game = game;
      this.hl = (function() {
        var _ref1;
        if ((_ref = (_ref1 = this.game.plugins) != null ? _ref1.get('voxel-highlight') : void 0) != null) {
          return _ref;
        } else {
          throw 'voxel-voila requires voxel-highlight plugin';
        }
      }).call(this);
      this.registry = (function() {
        var _ref2;
        if ((_ref1 = (_ref2 = this.game.plugins) != null ? _ref2.get('voxel-registry') : void 0) != null) {
          return _ref1;
        } else {
          throw 'voxel-voila requires voxel-registry plugin';
        }
      }).call(this);
      this.enable();
    }

    VoilaPlugin.prototype.enable = function() {
      var _this = this;
      return this.hl.on('highlight', this.onHighlight = function(pos) {
        var blockID, blockName;
        blockID = _this.game.getBlock(pos);
        blockName = _this.registry.getBlockName(blockID);
        return console.log(blockName);
      });
    };

    VoilaPlugin.prototype.disable = function() {
      return this.hl.removeListener('highlight', this.onHighlight);
    };

    return VoilaPlugin;

  })();

}).call(this);
